// fdb-medic/ui-svelte/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import DeathScreen from './components/DeathScreen.svelte';
  import MedicalPanel from './components/MedicalPanel.svelte';
  import InspectionPanel from './components/InspectionPanel.svelte';

  let currentView = 'hidden';
  let deathScreenData: any = { message: '', seconds: 0, canRespawn: false, medicsOnDuty: 0, translations: {} };
  let medicalData: any = { wounds: {}, treatments: [], infections: {}, bodyPartHealth: {}, injuryStates: {}, infectionStages: {}, bodyParts: {}, uiColors: {}, inventory: {}, bandageTypes: {}, isSelfExamination: false, translations: {} };
  let inspectionData: any = { playerName: '', vitals: {}, injuries: [], treatments: [], inventory: {}, translations: {} };
  
  let scale = 1;

  function handleResize() {
    const ratio = window.innerWidth / window.innerHeight;
    if (ratio > 1.78) {
      scale = (window.innerHeight * 1.777) / window.innerWidth;
    } else {
      scale = 1;
    }
  }

  function handleMessage(event: MessageEvent) {
    const { type, data } = event.data;
    
    switch (type) {
      case 'show-death-screen':
        currentView = 'death-screen';
        deathScreenData = data || {};
        break;
      case 'update-death-timer':
        deathScreenData = { ...deathScreenData, ...(data || {}) };
        break;
      case 'hide-death-screen':
        currentView = 'hidden';
        break;
      case 'show-medical-panel':
        currentView = 'medical-panel';
        medicalData = data || {};
        break;
      case 'show-inspection-panel':
        currentView = 'inspection-panel';
        inspectionData = data || {};
        break;
      case 'update-medical-data':
        medicalData = { ...medicalData, ...data };
        break;
      case 'hide-all':
        currentView = 'hidden';
        break;
    }
  }

  onMount(() => {
    window.addEventListener('resize', handleResize);
    handleResize();

    window.addEventListener('message', handleMessage);

    if (import.meta.env.DEV) {
      document.body.style.display = 'block';
      // development helpers
      (window as any).medical = {
        showDeathScreen: (data: any) => {
          window.postMessage({ type: 'show-death-screen', data }, '*');
        },
        showMedicalPanel: (data: any) => {
          window.postMessage({ type: 'show-medical-panel', data }, '*');
        },
        showInspectionPanel: (data: any) => {
          window.postMessage({ type: 'show-inspection-panel', data }, '*');
        },
        hideAll: () => {
          window.postMessage({ type: 'hide-all' }, '*');
        }
      };
    }
  });

  onDestroy(() => {
    window.removeEventListener('resize', handleResize);
    window.removeEventListener('message', handleMessage);
  });

  function hideAll() {
    const wasInspection = currentView === 'inspection-panel';
    currentView = 'hidden';
    
    try {
      fetch(`https://${(window as any).GetParentResourceName?.() || 'fdb-medic'}/close-medical-panel`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({})
      }).catch(() => {});
      
      if (wasInspection) {
        fetch(`https://${(window as any).GetParentResourceName?.() || 'fdb-medic'}/closeInspectionPanel`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({})
        }).catch(() => {});
      }
    } catch (error) {
      console.log('Would close panels');
    }
  }
</script>

<div class="App" style="width: 100vw; height: 100vh; position: fixed; top: 0; left: 0; display: flex; justify-content: center; align-items: center;">
  <div style="width: 100vw; height: 100vh; transform: scale({scale}); transform-origin: center center; position: relative;">
    
    {#if import.meta.env.DEV}
      <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.8); color: white; padding: 5px; z-index: 9999; font-size: 12px;">
        Current View: {currentView}
      </div>
    {/if}

    {#if currentView === 'death-screen'}
      <DeathScreen 
        message={deathScreenData.message}
        seconds={deathScreenData.seconds}
        canRespawn={deathScreenData.canRespawn}
        medicsOnDuty={deathScreenData.medicsOnDuty}
        translations={deathScreenData.translations}
      />
    {/if}

    {#if currentView === 'medical-panel'}
      <MedicalPanel
        wounds={medicalData.wounds}
        treatments={medicalData.treatments}
        infections={medicalData.infections}
        bodyPartHealth={medicalData.bodyPartHealth}
        injuryStates={medicalData.injuryStates}
        infectionStages={medicalData.infectionStages}
        bodyParts={medicalData.bodyParts}
        uiColors={medicalData.uiColors}
        inventory={medicalData.inventory}
        bandageTypes={medicalData.bandageTypes}
        isSelfExamination={medicalData.isSelfExamination}
        translations={medicalData.translations}
        onClose={hideAll}
      />
    {/if}

    {#if currentView === 'inspection-panel'}
      <InspectionPanel
        data={inspectionData}
        translations={inspectionData.translations}
        onClose={hideAll}
      />
    {/if}
  </div>
</div>

// fdb-medic/ui/src/App.tsx
import React, { useState, useEffect } from 'react';
import DeathScreen from './components/DeathScreen';
import MedicalPanel from './components/MedicalPanel';
import InspectionPanel from './components/InspectionPanel';

interface AppState {
  currentView: 'hidden' | 'death-screen' | 'medical-panel' | 'inspection-panel';
  deathScreenData: {
    message: string;
    seconds: number;
    canRespawn?: boolean;
    medicsOnDuty?: number;
    translations?: { [key: string]: string };
  };
  medicalData: {
    wounds: any;
    treatments: any[];
    infections?: any;
    bodyPartHealth?: any;
    injuryStates?: any;
    infectionStages?: any;
    bodyParts?: any;
    uiColors?: any;
    inventory?: any;
    bandageTypes?: any;
    isSelfExamination?: boolean;
    translations?: { [key: string]: string };
  };
  inspectionData: {
    playerName: string;
    vitals: any;
    injuries: any[];
    treatments: any[];
    inventory: any;
    translations?: { [key: string]: string };
    [key: string]: any; // Allow any additional properties from Lua
  };
}

function useWindowRatioScale() {
  const [scale, setScale] = useState(1);
  useEffect(() => {
    function handleResize() {
      const ratio = window.innerWidth / window.innerHeight;
      if (ratio > 1.78) {
        setScale((window.innerHeight * 1.777) / window.innerWidth);
      } else {
        setScale(1);
      }
    }
    window.addEventListener('resize', handleResize);
    handleResize();
    return () => window.removeEventListener('resize', handleResize);
  }, []);
  return scale;
}

function App() {
  const scale = useWindowRatioScale();
  const [state, setState] = useState<AppState>({
    currentView: 'hidden',
    deathScreenData: { message: '', seconds: 0, canRespawn: false, medicsOnDuty: 0, translations: {} },
    medicalData: { wounds: {}, treatments: [], infections: {}, bodyPartHealth: {}, injuryStates: {}, infectionStages: {}, bodyParts: {}, uiColors: {}, inventory: {}, bandageTypes: {}, isSelfExamination: false, translations: {} },
    inspectionData: { playerName: '', vitals: {}, injuries: [], treatments: [], inventory: {}, translations: {} }
  });

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      const { type, data } = event.data;
      
      switch (type) {
        case 'show-death-screen':
          setState(prev => ({
            ...prev,
            currentView: 'death-screen',
            deathScreenData: data
          }));
          break;
          
        case 'update-death-timer':
          setState(prev => ({
            ...prev,
            deathScreenData: { ...prev.deathScreenData, ...data }
          }));
          break;
          
        case 'hide-death-screen':
          setState(prev => ({
            ...prev,
            currentView: 'hidden'
          }));
          break;
          
        case 'show-medical-panel':
          setState(prev => ({
            ...prev,
            currentView: 'medical-panel',
            medicalData: data
          }));
          break;
          
        case 'show-inspection-panel':
          setState(prev => ({
            ...prev,
            currentView: 'inspection-panel',
            inspectionData: data
          }));
          break;
          
        case 'update-medical-data':
          console.log('Received update-medical-data:', data);
          console.log('Treatments in update:', data.treatments);
          setState(prev => ({
            ...prev,
            medicalData: {
              ...prev.medicalData,
              ...data
            }
          }));
          break;
          
        case 'hide-all':
          setState(prev => ({
            ...prev,
            currentView: 'hidden'
          }));
          break;
      }
    };

    window.addEventListener('message', handleMessage);
    
    // Make body visible in development
    if (process.env.NODE_ENV === 'development') {
      document.body.style.display = 'block';
    }

    return () => window.removeEventListener('message', handleMessage);
  }, []);

  const hideAll = () => {
    setState(prev => ({ ...prev, currentView: 'hidden' }));
    
    // Send message to client to disable NUI focus
    try {
      fetch(`https://${(window as any).GetParentResourceName()}/close-medical-panel`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({})
      }).catch(() => {});
    } catch (error) {
      // Fallback for development
      console.log('Would close medical panel');
    }
  };


  return (
    <div className="App" style={{ 
      width: '100vw', height: '100vh', position: 'fixed', top: 0, left: 0,
      display: 'flex', justifyContent: 'center', alignItems: 'center'
    }}>
      <div style={{
        width: '100vw', 
        height: '100vh',
        transform: `scale(${scale})`,
        transformOrigin: 'center center',
        position: 'relative'
      }}>
        {/* Debug info */}
        {process.env.NODE_ENV === 'development' && (
          <div style={{ position: 'fixed', top: 0, left: 0, background: 'rgba(0,0,0,0.8)', color: 'white', padding: '5px', zIndex: 9999, fontSize: '12px' }}>
            Current View: {state.currentView}
          </div>
        )}
      
      {state.currentView === 'death-screen' && (
        <DeathScreen
          message={state.deathScreenData.message}
          seconds={state.deathScreenData.seconds}
          canRespawn={state.deathScreenData.canRespawn}
          medicsOnDuty={state.deathScreenData.medicsOnDuty}
          translations={state.deathScreenData.translations}
        />
      )}
      
      {state.currentView === 'medical-panel' && (
        <MedicalPanel
          wounds={state.medicalData.wounds}
          treatments={state.medicalData.treatments}
          infections={state.medicalData.infections}
          bodyPartHealth={state.medicalData.bodyPartHealth}
          injuryStates={state.medicalData.injuryStates}
          infectionStages={state.medicalData.infectionStages}
          bodyParts={state.medicalData.bodyParts}
          uiColors={state.medicalData.uiColors}
          inventory={state.medicalData.inventory}
          bandageTypes={state.medicalData.bandageTypes}
          isSelfExamination={state.medicalData.isSelfExamination}
          translations={state.medicalData.translations}
          onClose={hideAll}
        />
      )}
      
      {state.currentView === 'inspection-panel' && (
        <InspectionPanel
          data={state.inspectionData}
          translations={state.inspectionData.translations}
          onClose={hideAll}
        />
      )}
      </div>
    </div>
  );
}

export default App;
